version: 2.1

orbs:
  android: circleci/android@2.0

jobs:
  build:
    executor:
      name: android/android-docker
      tag: 2024.01.1
    steps:
      - checkout
      - run:
          name: Create local.properties
          command: |
            echo "backend.url=${BACKEND_URL:-http://10.0.2.2:8001}" > android-app/local.properties
      - run:
          name: Grant execute permission for gradlew
          command: |
            cd android-app
            chmod +x gradlew
      - run:
          name: Build Debug APK
          command: |
            cd android-app
            ./gradlew assembleDebug
      - store_artifacts:
          path: android-app/app/build/outputs/apk/debug/app-debug.apk
          destination: doppelganger-debug.apk

workflows:
  build-android:
    jobs:
      - build